### ISSUE TITLE
Compiler is not optimized

### ISSUE THREAD

**Issue by Happi-cat** [sqlkata/querybuilder#124]
Atm compiler has `methodsCache ` of Dictionary type so its not thread-safe.
In other words compiler cannot be used as a singleton/static field and should be used per-thread. 
Otherwise different exceptions may be thrown, here is an example:
```
System.NullReferenceException: Object reference not set to an instance of an object.
  at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
  at SqlKata.Compilers.Compiler.FindCompilerMethodInfo(Type clauseType, String methodName)
  at SqlKata.Compilers.Compiler.CompileCondition(SqlResult ctx, AbstractCondition clause)
```

In case when u have 1-2 queries per request and tons of requests there will be only small boost in having that `methodCache`.

So probably ConcurrentDictionary can be used instead of Dictionary as a simple solution which will allow to save Compiler instance in a static field or use it as a singleton.
Or condition compilation can be redesign in any other way.

**Comment by ahmad-moussawi** [comment]
Thanks @Happi-cat, could you provide a PR to solve this, or can you give me some light on how to solve this ?

**Comment by Happi-cat** [comment]
Here are some my thoughts: https://github.com/sqlkata/querybuilder/pull/125

**Comment by ahmad-moussawi** [comment]
@Happi-cat reviewing this still not catching why the dictionary is not thread-safe, I need to build something similar but still not catching the idea :), could you give me some hints, or points me to a link to understand it more, appreciate your effort. thanks.
