### ISSUE TITLE
`InsertGetId` throws a System.InvalidOperationException or `Sequence contains no elements`

### ISSUE THREAD

**Issue by KLia** [sqlkata/querybuilder#247]
I am having some issues when executing `InsertGetId`. It seems like the entry is created in the database, but it is still throwing an exception.

There seems to be two different exceptions, and I can't see a pattern when one is thrown over the other. I'm running .NetCore 2.2 and SqlKata 1.1.7, and am initializing the QueryFactory using DependencyInjection as stated here: 
https://sqlkata.com/docs/execution/setup#aspnet-core-di-container

Any ideas on what might be causing this?
I'm pasting the stack trace that I get below

```exceptionMessage: Sequence contains no elements
exceptionType: System.InvalidOperationException
stacktrace:   at System.Linq.Enumerable.First[TSource](IEnumerable'1 source)
   at Dapper.SqlMapper.ThrowZeroRows(Row row) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1160
   at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 526
   at SqlKata.Execution.QueryExtensionsAsync.InsertGetIdAsync[T](Query query, Object data) in C:\projects\querybuilder\SqlKata.Execution\Query.Extensions.Async.cs:line 186

---------

exceptionMessage: Connection must be valid and open.
exceptionType:System.InvalidOperationException
stacktrace:   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.CheckState()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 526
   at SqlKata.Execution.QueryExtensionsAsync.InsertGetIdAsync[T](Query query, Object data) in C:\projects\querybuilder\SqlKata.Execution\Query.Extensions.Async.cs:line 186```

**Comment by ahmad-moussawi** [comment]
as per the exception, it seems you are using a closed connection, could you elaborate more, could you share a project with the issue?

**Comment by KLia** [comment]
I understand that that might be the issue for the second exception, but not for the first. 
Unfortunately I cannot share the whole project, but I can share some code snippets.

In `Startup.cs`

```
services.AddSingleton(
     provider =>
     {
         var connection = new MySqlConnection(Configuration["MyConnectionString"]);

         var queryFactory = new QueryFactory(connection, new MySqlCompiler());

         return queryFactory;
     });
```

In our DataAccessor class (which is being initialized by the DI as "Scoped"), we have:

```
public DataAccessor(QueryFactory queryFactory)
   {
      this.queryFactory = queryFactory;
   }
```

And in our method:

```
public async Task<int> CreateActivityAsync(Activity activity)
        {
            return await queryFactory.Query("activity")
            .InsertGetIdAsync<int>(
                new
                {
                    Created = activity.Created.UtcDateTime,
                    LastActivity = activity.LastActivity.UtcDateTime,
                    Name = activity.Name,
                    Type = activity.ConversationType
                }).ConfigureAwait(false);
        }
```

The entry is being created in the database, but it throws this exception anyway.
I hope this clears it up our issue a bit more.

**Comment by ahmad-moussawi** [comment]
As far as I know, registering the database as Singleton is an extremly bad idea,
check this thread for more info
https://stackoverflow.com/a/1557614/1104402

**Comment by KLia** [comment]
But isn't the Singleton here only handling the QueryFactory, and not the connection itself?

**Comment by ahmad-moussawi** [comment]
No one connection is created (during the app startup) and shared with all requests.
```cs
var connection = new MySqlConnection(Configuration["MyConnectionString"]);
```

**Comment by KLia** [comment]
If that's the case, I can see how it can go terribly bad!
Thanks, I will change it.
