### ISSUE TITLE
Naming strategy with ORACLE

### ISSUE THREAD

**Issue by fairking** [sqlkata/querybuilder#391]
SQLKata 2.2.0
Oracle 18xe
Compiler only with no execution.

I have an issue. 
Having names in my app like "snake_case" the SQLKata creates the following query:
`select "my_column" from "USER1"."snake_case"` 
which causes the sql error "table or view not found".
The right solution is to have a query without quotes like: `select my_column from USER1.snake_case`.

Along with sqlkata I am using NHibernate with ImprovedNamingStrategy. NHibernate is working fine with those names and produces the queries with no quotes (eg. running QueryOver).
Also my app is using SQLServer and Postgres. Both of them are working with no issues.

Is it possible to tell SQLKata to not wrap names into quotes? Or maybe there is another solution for that. Thanks for any help.

**Comment by ahmad-moussawi** [comment]
You can create your own Oracle compiler and override the default Identifiers, and use it instead of the default Oracle Compiler

```cs
    public class MyOracleCompiler : OracleCompiler
    {
        MyOracleCompiler()
        {
            OpeningIdentifier = "";
            ClosingIdentifier = "";
        }
    }
```
I think this what you need in your case

**Comment by fairking** [comment]
Tried what you suggested. But I am ending up with the following error:
```
System.ArgumentException: String cannot be of zero length. (Parameter 'oldValue')
   at System.String.Replace(String oldValue, String newValue)
   at SqlKata.Compilers.Compiler.WrapValue(String value) in C:\Projects\querybuilder\QueryBuilder\Compilers\Compiler.cs:line 837
   at SqlKata.Compilers.Compiler.CompileColumns(SqlResult ctx) in C:\Projects\querybuilder\QueryBuilder\Compilers\Compiler.cs:line 508
   at SqlKata.Compilers.Compiler.CompileSelectQuery(Query query) in C:\Projects\querybuilder\QueryBuilder\Compilers\Compiler.cs:line 190
   at SqlKata.Compilers.OracleCompiler.CompileSelectQuery(Query query) in C:\Projects\querybuilder\QueryBuilder\Compilers\OracleCompiler.cs:line 24
   at SqlKata.Compilers.Compiler.CompileRaw(Query query) in C:\Projects\querybuilder\QueryBuilder\Compilers\Compiler.cs:line 120
   at SqlKata.Compilers.Compiler.Compile(Query query) in C:\Projects\querybuilder\QueryBuilder\Compilers\Compiler.cs:line 153
```
![image](https://user-images.githubusercontent.com/13495631/84264107-865c9280-ab18-11ea-9c11-b369c9cc51ff.png)

**Comment by ahmad-moussawi** [comment]
Happy to hear that!, I will close it for now.
Thanks for your feedback.
