### ISSUE TITLE
Count<T> throws null reference with no rows when upgrading to 2.3.8

### ISSUE THREAD

**Issue by Myrmex** [sqlkata/querybuilder#600]
I'm having an issue upgrading from release 2.3.7 to 2.3.8 in using `Count` when no rows are returned, as it now seems to throw a null reference exception.

As a sample, consider this scenario: I often use the execution package of SqlKata (with PgSql) to:

1. dynamically build some query without the select clause.
2. clone it and add a `.Count<int>(new[]{"fieldname"})` to count the results.
3. if results are present, complete the query with `.Select`, `.OrderBy`, and `.Skip`/`.Limit`, and run it to fetch rows.

This pattern is essentially for paging, where the same query must be executed once (without sorting and paging) to get the total, retrieving just the rows count; and then a second time to get the specified page. It worked fine, but something seems now broken in 2.3.8, because when I execute `Count` for a query which returns no rows, I get a null exception, e.g.:

```cs
// this throws when no rows are returned
int total = query.Clone().Count<int>(new[] { "document_id" });
```

```txt
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SqlKata.Execution
  StackTrace:
   at SqlKata.Execution.QueryExtensions.CreateQueryFactory(XQuery xQuery)
   at SqlKata.Execution.QueryExtensions.CreateQueryFactory(Query query)
   at SqlKata.Execution.QueryExtensions.Count[T](Query query, String[] columns, IDbTransaction transaction, Nullable`1 timeout)
```

**Comment by Myrmex** [comment]
Thank you, here is my relevant code. First, this is a trivial utility method to get a query factory ready to use (that's a base class for different repositories):


```cs
protected QueryFactory GetQueryFactory()
{
    var qf = new QueryFactory(GetConnection(), SqlCompiler);
    qf.Connection.Open();
    return qf;
}
```

The following method is used to dynamically apply filters from a filters object (`filter`) to a query (`query`):

```cs
private static void ApplyTextUnitFilter(TextUnitFilter filter, Query query)
{
    // analyzed
    if (filter.Analyzed != null)
    {
        // analyzed, eventually with specific outcome(s)
        if (filter.Analyzed.Value)
        {
            query.WhereNotNull("au.response_type");

            // filter by outcome if requested
            List<AnalysisResponseType> whiteTypes = new();
            List<AnalysisResponseType> blackTypes = new();

            if (filter.Failed == true)
                whiteTypes.Add(AnalysisResponseType.Failure);
            else if (filter.Failed == false)
                blackTypes.Add(AnalysisResponseType.Failure);

            if (filter.Incomplete == true)
                whiteTypes.Add(AnalysisResponseType.Incomplete);
            else if (filter.Incomplete == false)
                blackTypes.Add(AnalysisResponseType.Incomplete);

            if (filter.Complete == true)
                whiteTypes.Add(AnalysisResponseType.Complete);
            else if (filter.Complete == false)
                blackTypes.Add(AnalysisResponseType.Complete);

            if (whiteTypes.Count > 0)
                query.WhereIn("au.response_type", whiteTypes);
            if (blackTypes.Count > 0)
                query.WhereNotIn("au.response_type", blackTypes);
        }
        // not analyzed, no outcome
        else query.WhereNull("au.response_type");
    }

    // edited
    if (filter.Edited != null)
    {
        if (filter.Edited == true)
            query.WhereNotNull("tu.last_modified");
        else
            query.WhereNull("tu.last_modified");
    }

    // min
    if (filter.MinUnitNumber > 0)
        query.Where("tu.number", ">=", filter.MinUnitNumber);

    // max
    if (filter.MaxUnitNumber > 0)
        query.Where("tu.number", "<=", filter.MaxUnitNumber);
}
```

This is the method failing with the new version: it gets a number of "text units" from a document using the specified filter. To this end, it first builds a query; then, it applies filters to it, using the above method; then it gets the total count, and later fetches the rows required for the requested page:

```cs
public DataPage<TextUnitInfo> GetTextUnits(int documentId,
    TextUnitFilter filter)
{
    if (filter == null) throw new ArgumentNullException(nameof(filter));

    using QueryFactory qf = GetQueryFactory();

    var query = qf.Query("text_unit AS tu")
                  .LeftJoin("text_unit_attribute AS tua",
                    j => j.On("tu.document_id", "tua.document_id")
                          .On("tu.number", "tua.unit_number"))
                  .LeftJoin("analyzed_unit AS au",
                    j => j.On("tu.document_id", "au.document_id")
                          .On("tu.number", "au.unit_number"))
                  .Where("tu.document_id", documentId)
                  .Where("tua.name", InputTextAttribute.NR_ATTRIBUTE);
    ApplyTextUnitFilter(filter, query);

    // get total
    int total = query.Clone().Count<int>(new[] { "tu.document_id" });
    if (total == 0)
    {
        return new DataPage<TextUnitInfo>(
            filter.PageNumber, filter.PageSize, 0,
            Array.Empty<TextUnitInfo>());
    }

    // complete query and get page items
    query.Select("tu.document_id", "tu.number", "tu.text",
        "tu.source_text", "tu.last_modified", "tua.value AS label",
        "au.response_type", "au.message")
        .OrderBy("tu.number")
        .Skip(filter.GetSkipCount()).Limit(filter.PageSize);

    List<TextUnitInfo> items = new(filter.PageSize);
    foreach (var d in query.Get())
    {
        items.Add(new TextUnitInfo
        {
            DocumentId = d.document_id,
            Number = d.number,
            Text = d.text,
            SourceText = d.source_text,
            LastModified = d.last_modified,
            Label = d.label,
            ResponseType = (AnalysisResponseType?)d.response_type,
            Message = d.message
        });
    }
    return new DataPage<TextUnitInfo>(filter.PageNumber, filter.PageSize,
        total, items);
}
```

**Comment by ahmad-moussawi** [comment]
I've released a new release, 2.3.9 can you upgrade and check if the issue persist?

**Comment by Myrmex** [comment]
Thank you, this seems to work, or at least all my unit tests now go green.

**Comment by ahmad-moussawi** [comment]
Ok great, I will close the issue then, thanks for reporting!
